<template>
    <div id="filelist" class="wrap">
        <h1>{{ msg }}</h1>
        <div class="header">
            <p>진행중 : <span class="ing_n">{{ ingCount }}</span>p / 미완료 : <span class="notfin">{{ notCompleteCount }}</span>p / 완료 : <span class="fin" id="fin">{{ completeCount }}</span>p / 전체 : <span class="total_n">{{ totalCount }}</span>p</p>
            <p>진행율 : <span class="per">{{ per }} %</span></p>
        </div>
        <div class="items_w">
            <table class="codingitems">
                <colgroup>
                    <col style="width:40px">
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col style="width:120px">
                    <col style="width:200px">
                    <col style="width:50px">
                    <col style="width:80px">
                    <col style="width:80px">
                    <col style="width:50px">
                    <col>
                </colgroup>
                <thead>
                    <tr>
                        <th rowspan="2">no.</th>
                        <th colspan="6">navi</th>
                        <th rowspan="2">화면ID</th>
                        <th rowspan="2">Path</th>
                        <th rowspan="2">확인</th>
                        <th rowspan="2">시작일</th>
                        <th rowspan="2">종료일</th>
                        <th rowspan="2">상태</th>
                        <th rowspan="2">etc.</th>
                    </tr>
                    <tr>
                        <th class="lineli">1depth</th>
                        <th>2depth</th>
                        <th>3depth</th>
                        <th>4depth</th>
                        <th>5depth</th>
                        <th>6depth</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="(item, index) in items" :key="item.id" :class="item.division">
                        <td class="no">{{ index + 1 }}</td>
                        <td>{{ item.depth1 }}</td>
                        <td>{{ item.depth2 }}</td>
                        <td>{{ item.depth3 }}</td>
                        <td>{{ item.depth4 }}</td>
                        <td>{{ item.depth5 }}</td>
                        <td>{{ item.depth6 }}</td>
                        <td class="start_date">
                            <p v-for="(itemId, itemIndex) in item.s_id" :key="itemIndex">{{ itemId }}</p>
                        </td>
                        <td class="link"><a :href="item.link" target="_blank">{{ item.link }}</a></td>
                        <td class="ing start_date">{{ item.resize }}</td>
                        <td class="start_date">{{ item.s_date }}</td>
                        <td class="end_date">{{ item.e_date }}</td>
                        <td class="work" :class="item.status" v-html="item.ing"></td>
                        <td class="etc" v-html="item.etc"></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</template>
<script lang="ts">
import { defineComponent } from 'vue'
export default defineComponent({
    name: 'FileItems',
    data () {
        return {
            msg: '한화 작업 목록',
            isData: true,
            items: [
                {
                    depth1: 'Publishing Guide',
                    depth2: '공통 가이드',
                    link: '/guide',
                    resize: '',
                    s_date: '2022.03.14',
                    e_date: '',
                    ing: '진행중',
                    status: 'ing',
                    etc: '',
                },
                {
                    division: 'division',
                    depth1: 'popup',
                    depth2: '팝업 모음 목록',
                    s_id: ['popup all'],
                    link: '/layout/popupList',
                    resize: '',
                    s_date: '2022.04.14',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: 'division',
                    depth1: 'layout',
                    s_id: ['HwLayout'],
                    link: '/test/testView',
                    resize: '',
                    s_date: '2022.03.14',
                    e_date: '',
                    ing: '진행중',
                    status: 'ing',
                    etc: '',
                },
                {
                    division: 'division',
                    depth1: 'login',
                    depth2: '로그인',
                    s_id: ['login'],
                    link: '/login/login1',
                    resize: '',
                    s_date: '2022.03.19',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'login',
                    depth2: '로그인',
                    s_id: ['login'],
                    link: '/login/login2',
                    resize: '',
                    s_date: '2022.03.20',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'login',
                    depth2: '로그인',
                    s_id: ['login'],
                    link: '/login/login3',
                    resize: '',
                    s_date: '2022.12.21',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: 'division',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin1'],
                    link: '/admin/adm_01',
                    resize: '',
                    s_date: '2022.03.20',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin2'],
                    link: '/admin/adm_02',
                    resize: '',
                    s_date: '2022.04.01',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin3'],
                    link: '/admin/adm_03',
                    resize: '',
                    s_date: '2022.04.05',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin4'],
                    link: '/admin/adm_04',
                    resize: '',
                    s_date: '2022.04.05',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin5'],
                    link: '/admin/adm_05',
                    resize: '',
                    s_date: '2022.04.05',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin7'],
                    link: '/admin/adm_07',
                    resize: '',
                    s_date: '2022.04.06',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin7_2'],
                    link: '/admin/adm_07_2',
                    resize: '',
                    s_date: '2022.04.06',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin7_3'],
                    link: '/admin/adm_07_3',
                    resize: '',
                    s_date: '2022.04.06',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin7_4'],
                    link: '/admin/adm_07_4',
                    resize: '',
                    s_date: '2022.04.06',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin7_5'],
                    link: '/admin/adm_07_5',
                    resize: '',
                    s_date: '2022.04.07',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin8'],
                    link: '/admin/adm_08',
                    resize: '',
                    s_date: '2022.04.05',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin10'],
                    link: '/admin/adm_10',
                    resize: '',
                    s_date: '2022.04.06',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin11'],
                    link: '/admin/adm_11',
                    resize: '',
                    s_date: '2022.04.22',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin12'],
                    link: '/admin/adm_12',
                    resize: '',
                    s_date: '2022.04.27',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin13'],
                    link: '/admin/adm_13',
                    resize: '',
                    s_date: '2022.04.27',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin14'],
                    link: '/admin/adm_14',
                    resize: '',
                    s_date: '2022.04.27',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin15'],
                    link: '/admin/adm_15',
                    resize: '',
                    s_date: '2022.04.27',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin16'],
                    link: '/admin/adm_16',
                    resize: '',
                    s_date: '2022.04.27',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin17'],
                    link: '/admin/adm_17',
                    resize: '',
                    s_date: '2022.08.10',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin18'],
                    link: '/admin/adm_18',
                    resize: '',
                    s_date: '2022.08.16',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin19'],
                    link: '/admin/adm_19',
                    resize: '',
                    s_date: '2022.08.16',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin20'],
                    link: '/admin/adm_20',
                    resize: '',
                    s_date: '2022.08.16',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin21'],
                    link: '/admin/adm_21',
                    resize: '',
                    s_date: '2022.08.12',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin22'],
                    link: '/admin/adm_22',
                    resize: '',
                    s_date: '2022.08.12',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin23'],
                    link: '/admin/adm_23',
                    resize: '',
                    s_date: '2022.08.12',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin24'],
                    link: '/admin/adm_24',
                    resize: '',
                    s_date: '2022.08.12',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin25'],
                    link: '/admin/adm_25',
                    resize: '',
                    s_date: '2022.08.12',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin26'],
                    link: '/admin/adm_26',
                    resize: '',
                    s_date: '2022.08.12',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    s_id: ['admin27'],
                    link: '/admin/adm_27',
                    resize: '',
                    s_date: '2022.08.12',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    depth3: '대용량 파일 다운로드',
                    s_id: ['admin28'],
                    link: '/admin/adm_28',
                    resize: '',
                    s_date: '2022.11.22',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'admin',
                    depth2: '관리자',
                    depth3: '과제 태그 관리',
                    s_id: ['admin29'],
                    link: '/admin/adm_29',
                    resize: '',
                    s_date: '2022.12.14',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },

                {
                    division: 'division',
                    depth1: 'main',
                    s_id: ['Home'],
                    link: '/main',
                },
                {
                    division: '',
                    depth1: 'main',
                    s_id: ['Home'],
                    link: '/mainType2',
                },
                {
                    division: '',
                    depth1: 'main',
                    depth2: '임시',
                    s_id: ['Home'],
                    link: '/main2',
                },
                {
                    division: '',
                    depth1: 'main',
                    s_id: ['comingSoon'],
                    link: '/main/comingSoonBoard',
                    resize: '',
                    s_date: '2022.07.18',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'main',
                    s_id: ['comingSoon'],
                    link: '/main/comingSoonApproval',
                    resize: '',
                    s_date: '2022.07.18',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'main',
                    s_id: ['comingSoon'],
                    link: '/main/comingSoonShare',
                    resize: '',
                    s_date: '2022.07.18',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'main',
                    s_id: ['comingSoon'],
                    link: '/main/comingSoonSupply',
                    resize: '',
                    s_date: '2022.07.18',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'main',
                    s_id: ['comingSoon'],
                    link: '/main/comingSoonMail',
                    resize: '',
                    s_date: '2022.07.18',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'main',
                    s_id: ['cMain'],
                    link: '/main/cMain',
                    resize: '',
                    s_date: '2022.05.30',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'main setting',
                    s_id: ['main setting'],
                    link: '/main/mainSetting',
                    resize: '',
                    s_date: '2022.04.15',
                    e_date: '',
                    ing: '진행중',
                    status: 'ing',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'main',
                    depth2: '메일 사용현황',
                    s_id: ['mail use'],
                    link: '/main/mailUse',
                    resize: '',
                    s_date: '2022.10.03',
                    e_date: '',
                    ing: '진행중',
                    status: 'ing',
                    etc: '',
                },
                {
                    division: 'division',
                    depth1: 'board main',
                    depth2: '게시판',
                    depth3: '메인',
                    s_id: ['board setting'],
                    link: '/board/boardMain',
                    resize: '',
                    s_date: '2022.04.19',
                    e_date: '',
                    ing: '진행중',
                    status: 'ing',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'board notice',
                    depth2: '게시판',
                    depth3: '공지사항 - 카드형',
                    s_id: ['board'],
                    link: '/board/boardNotice',
                    resize: '',
                    s_date: '2022.04.22',
                    e_date: '',
                    ing: '진행중',
                    status: 'ing',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'board notice',
                    depth2: '게시판',
                    depth3: '공지사항 - 목록형',
                    s_id: ['board'],
                    link: '/board/boardNoticeList',
                    resize: '',
                    s_date: '2022.06.22',
                    e_date: '',
                    ing: '진행중',
                    status: 'ing',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'board notice',
                    depth2: '게시판',
                    depth3: '상세보기',
                    s_id: ['board'],
                    link: '/board/boardNoticeView',
                    resize: '',
                    s_date: '2022.04.22',
                    e_date: '',
                    ing: '진행중',
                    status: 'ing',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'board notice',
                    depth2: '게시판',
                    depth3: '작성하기',
                    s_id: ['board'],
                    link: '/board/boardNoticeWrite',
                    resize: '',
                    s_date: '2022.04.28',
                    e_date: '',
                    ing: '진행중',
                    status: 'ing',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'board favorite',
                    depth2: '게시판',
                    depth3: '즐겨찾기',
                    s_id: ['board'],
                    link: '/board/boardFavor',
                    resize: '',
                    s_date: '2022.04.29',
                    e_date: '',
                    ing: '진행중',
                    status: 'ing',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'board search',
                    s_id: ['board'],
                    depth2: '게시판',
                    depth3: '검색',
                    link: '/board/boardSearch',
                    resize: '',
                    s_date: '2022.06.28',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: 'division',
                    depth1: 'approval list',
                    depth2: '전자결재',
                    depth3: '리스트',
                    s_id: ['approval'],
                    link: '/approval/approvalList',
                    resize: '',
                    s_date: '2022.05.11',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'approval view',
                    depth2: '전자결재',
                    depth3: '상세보기',
                    s_id: ['approval'],
                    link: '/approval/approvalView',
                    resize: '',
                    s_date: '2022.05.11',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'approval write',
                    depth2: '전자결재',
                    depth3: '작성하기',
                    s_id: ['approval'],
                    link: '/approval/approvalWrite',
                    resize: '',
                    s_date: '2022.05.16',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'approval form selected',
                    depth2: '전자결재',
                    depth3: '양식 선택하기',
                    s_id: ['approval'],
                    link: '/approval/approvalFormSelected',
                    resize: '',
                    s_date: '2022.05.16',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'approval external list',
                    depth2: '전자결재',
                    depth3: '대외문서 관리 목록',
                    s_id: ['approval'],
                    link: '/approval/externalList',
                    resize: '',
                    s_date: '2022.09.16',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                // {
                //     division: '',
                //     depth1: 'approval error',
                //     s_id: ['approval'],
                //     link: '/approval/approvalError',
                //     resize: '',
                //     s_date: '2022.06.23',
                //     e_date: '',
                //     ing: '진행중',
                //     status: 'ing',
                //     etc: '',
                // },
                //cluster
                {
                    division: 'division',
                    depth1: 'cluster',
                    depth2: 'team',
                    depth3: '중점 task',
                    s_id: ['cluster001'],
                    link: '/cluster/cluster001',
                    resize: '',
                    s_date: '2022.05.16',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'cluster',
                    depth2: 'team',
                    depth3: '과제',
                    s_id: ['cluster001_02'],
                    link: '/cluster/cluster001_02',
                    resize: '',
                    s_date: '2022.12.13',
                    e_date: '2022.12.13',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'cluster',
                    depth2: 'team',
                    depth3: '조직',
                    s_id: ['cluster002'],
                    link: '/cluster/cluster002',
                    resize: '',
                    s_date: '2022.05.18',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'cluster',
                    s_id: ['cluster003'],
                    depth2: 'team',
                    depth3: '조직 - select box 형태',
                    link: '/cluster/cluster003',
                    resize: '',
                    s_date: '2022.05.18',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'cluster',
                    depth2: 'team',
                    depth3: '클러스터명',
                    s_id: ['cluster004'],
                    link: '/cluster/cluster004',
                    resize: '',
                    s_date: '2022.05.18',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'cluster',
                    s_id: ['HIS_01'],
                    depth2: 'team',
                    depth3: '중점 task history',
                    link: '/cluster/HIS_01',
                    resize: '',
                    s_date: '2022.05.19',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'cluster',
                    s_id: ['HIS_01_02'],
                    depth2: 'team',
                    depth3: '과제',
                    link: '/cluster/HIS_01_02',
                    resize: '',
                    s_date: '2022.12.13',
                    e_date: '2022.12.13',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'cluster',
                    s_id: ['HIS_01_03'],
                    depth2: 'team',
                    depth3: '과제 상세',
                    link: '/cluster/HIS_01_03',
                    resize: '',
                    s_date: '2022.12.13',
                    e_date: '2022.12.13',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'cluster',
                    depth2: 'team',
                    depth3: '중점 task history',
                    depth4: 'no data',
                    s_id: ['HIS_02'],
                    link: '/cluster/HIS_02',
                    resize: '',
                    s_date: '2022.05.19',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: 'division',
                    depth1: 'node',
                    s_id: ['Node001'],
                    link: '/node/Node001',
                    resize: '',
                    s_date: '2022.05.19',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'node',
                    s_id: ['Node001B'],
                    link: '/node/Node001B',
                    resize: '',
                    s_date: '2022.05.19',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'node',
                    s_id: ['Node'],
                    link: '/node/Node_nodata',
                    resize: '',
                    s_date: '2022.05.19',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: 'division',
                    depth1: 'task',
                    s_id: ['NTS_01'],
                    link: '/task/NTS_01',
                    resize: '',
                    s_date: '2022.05.19',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'task',
                    s_id: ['NTS_01B'],
                    link: '/task/NTS_01B',
                    resize: '',
                    s_date: '2022.05.20',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'task',
                    depth2: '과제',
                    s_id: ['NTS_01B_02'],
                    link: '/task/NTS_01B_02',
                    resize: '',
                    s_date: '2022.12.12',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'task',
                    s_id: ['NTS_01C'],
                    link: '/task/NTS_01C',
                    resize: '',
                    s_date: '2022.05.20',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'task',
                    depth2: '과제',
                    s_id: ['NTS_01C_02'],
                    link: '/task/NTS_01C_02',
                    resize: '',
                    s_date: '2022.12.12',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'task',
                    s_id: ['NTS_01D'],
                    link: '/task/NTS_01D',
                    resize: '',
                    s_date: '2022.05.20',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'task',
                    s_id: ['NTS_01'],
                    link: '/task/NTS_01_nodata',
                    resize: '',
                    s_date: '2022.05.20',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: 'division',
                    depth1: 'my',
                    s_id: ['MYS_002'],
                    link: '/my/MYS_002',
                    resize: '',
                    s_date: '2022.05.23',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'my',
                    s_id: ['MYS_002'],
                    link: '/my/MYS_002_nodata',
                    resize: '',
                    s_date: '2022.05.23',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'my',
                    s_id: ['MYS_001'],
                    link: '/my/MYS_001',
                    resize: '',
                    s_date: '2022.05.23',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'my',
                    s_id: ['MYS_001B'],
                    link: '/my/MYS_001B',
                    resize: '',
                    s_date: '2022.05.23',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'my',
                    s_id: ['MYS_001'],
                    link: '/my/MYS_001_nodata',
                    resize: '',
                    s_date: '2022.05.23',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'my',
                    s_id: ['MYS_001B'],
                    link: '/my/MYS_001B_nodata',
                    resize: '',
                    s_date: '2022.05.23',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: 'division',
                    depth1: 'task log',
                    depth2: '보드 에디터',
                    s_id: ['task_log'],
                    link: '/taskLog/taskLog',
                    resize: '',
                    s_date: '2022.05.24',
                    e_date: '',
                    ing: '진행중',
                    status: 'ing',
                    etc: '',
                },
                {
                    division: 'division',
                    depth1: 'search',
                    depth2: '태그 검색',
                    s_id: ['SHS_01'],
                    link: '/search/SHS_01',
                    resize: '',
                    s_date: '2022.05.27',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'search',
                    depth2: '검색 no data',
                    s_id: ['SHS_01_nodata'],
                    link: '/search/SHS_01_nodata',
                    resize: '',
                    s_date: '2022.05.27',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'search',
                    depth2: '검색 no data',
                    depth3: 'no data 메세지 다른 타입',
                    s_id: ['SHS_01B_nodata'],
                    link: '/search/SHS_01B_nodata',
                    resize: '',
                    s_date: '2022.05.27',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: 'division',
                    depth1: 'alarm',
                    depth2: '알림',
                    s_id: ['ALS_01'],
                    link: '/alarm/ALS_01',
                    resize: '',
                    s_date: '2022.05.25',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'alarm',
                    depth2: '알림',
                    s_id: ['ALS_DM_1'],
                    link: '/alarm/ALS_DM_1',
                    resize: '',
                    s_date: '2022.05.25',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'alarm',
                    depth2: '알림',
                    s_id: ['ALS_DM_2'],
                    link: '/alarm/ALS_DM_2',
                    resize: '',
                    s_date: '2022.05.25',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'alarm',
                    depth2: '알림',
                    s_id: ['ALS_DM_3'],
                    link: '/alarm/ALS_DM_3',
                    resize: '',
                    s_date: '2022.05.25',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'alarm',
                    depth2: '알림',
                    s_id: ['ALS_DM_4'],
                    link: '/alarm/ALS_DM_4',
                    resize: '',
                    s_date: '2022.05.25',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'alarm',
                    depth2: '알림',
                    s_id: ['ALS_DM_5'],
                    link: '/alarm/ALS_DM_5',
                    resize: '',
                    s_date: '2022.05.25',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'alarm',
                    depth2: '알림',
                    s_id: ['ALS_DM_6'],
                    link: '/alarm/ALS_DM_6',
                    resize: '',
                    s_date: '2022.05.25',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'alarm',
                    depth2: '알림',
                    s_id: ['ALS_DM_7'],
                    link: '/alarm/ALS_DM_7',
                    resize: '',
                    s_date: '2022.09.20',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'alarm',
                    depth2: '알림',
                    s_id: ['ALS_DM_8'],
                    link: '/alarm/ALS_DM_8',
                    resize: '',
                    s_date: '2022.09.21',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'alarm',
                    depth2: '알림',
                    s_id: ['ALS_DM_9'],
                    link: '/alarm/ALS_DM_9',
                    resize: '',
                    s_date: '2022.09.21',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'alarm',
                    depth2: '알림',
                    s_id: ['ALS_DM_10'],
                    link: '/alarm/ALS_DM_10',
                    resize: '',
                    s_date: '2022.09.21',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'alarm',
                    depth2: '알림',
                    s_id: ['ALS_DM_11'],
                    link: '/alarm/ALS_DM_11',
                    resize: '',
                    s_date: '2022.09.21',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'alarm',
                    depth2: '알림',
                    s_id: ['ALS_DM_12'],
                    link: '/alarm/ALS_DM_12',
                    resize: '',
                    s_date: '2022.09.21',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'alarm',
                    depth2: '알림',
                    s_id: ['ALS_DM_13'],
                    link: '/alarm/ALS_DM_13',
                    resize: '',
                    s_date: '2022.09.21',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'alarm',
                    depth2: '알림',
                    s_id: ['ALS_DM_14'],
                    link: '/alarm/ALS_DM_14',
                    resize: '',
                    s_date: '2022.12.16',
                    e_date: '2022.12.16',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: 'division',
                    depth1: 'share',
                    depth2: '정보공유',
                    s_id: ['SHR_01'],
                    link: '/share/SHR_01',
                    resize: '',
                    s_date: '2022.05.26',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'share',
                    depth2: '정보공유',
                    s_id: ['SHR_02'],
                    link: '/share/SHR_02',
                    resize: '',
                    s_date: '2022.05.26',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: 'division',
                    depth1: 'people',
                    s_id: ['people'],
                    link: '/people/people',
                    resize: '',
                    s_date: '2022.05.26',
                    e_date: '',
                    ing: '진행중',
                    status: 'ing',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'people',
                    s_id: ['people'],
                    link: '/people/people_nodata',
                    resize: '',
                    s_date: '2022.05.26',
                    e_date: '',
                    ing: '진행중',
                    status: 'ing',
                    etc: '',
                },
                {
                    division: 'division',
                    depth1: 'stage',
                    s_id: ['CLS_02'],
                    link: '/stage/CLS_02',
                    resize: '',
                    s_date: '2022.05.26',
                    e_date: '',
                    ing: '진행중',
                    status: 'ing',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'stage',
                    s_id: ['CLS_03'],
                    link: '/stage/CLS_03',
                    resize: '',
                    s_date: '2022.05.26',
                    e_date: '',
                    ing: '진행중',
                    status: 'ing',
                    etc: '',
                },
                {
                    division: 'division',
                    depth1: 'collab',
                    depth2: '협업보드',
                    s_id: ['collabBoard'],
                    link: '/collab/collabBoard',
                    resize: '',
                    s_date: '2022.06.01',
                    e_date: '',
                    ing: '진행중',
                    status: 'ing',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'collab',
                    depth2: '협업보드',
                    s_id: ['collabBoard2'],
                    link: '/collab/collabBoard2',
                    resize: '',
                    s_date: '2022.06.01',
                    e_date: '',
                    ing: '진행중',
                    status: 'ing',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'collab',
                    depth2: '협업보드',
                    s_id: ['BDS034'],
                    link: '/collab/BDS034',
                    resize: '',
                    s_date: '2022.06.22',
                    e_date: '',
                    ing: '진행중',
                    status: 'ing',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'collab',
                    depth2: '협업보드',
                    s_id: ['BDS035'],
                    link: '/collab/BDS035',
                    resize: '',
                    s_date: '2022.06.22',
                    e_date: '',
                    ing: '진행중',
                    status: 'ing',
                    etc: '',
                },
                {
                    division: 'division',
                    depth1: 'ttsearch',
                    depth2: '통합검색',
                    s_id: ['TS_01'],
                    link: '/ttsearch/TS_01',
                    resize: '',
                    s_date: '2022.05.31',
                    e_date: '',
                    ing: '진행중',
                    status: 'ing',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'ttsearch',
                    depth2: '통합검색',
                    s_id: ['TS_02'],
                    link: '/ttsearch/TS_02',
                    resize: '',
                    s_date: '2022.05.31',
                    e_date: '',
                    ing: '진행중',
                    status: 'ing',
                    etc: '',
                },
                {
                    division: 'division',
                    depth1: 'support',
                    depth2: '임직원서비스',
                    s_id: ['staffList'],
                    link: '/support/staffList',
                    resize: '',
                    s_date: '2022.06.23',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'support',
                    depth2: '업무지원',
                    s_id: ['workList'],
                    link: '/support/workList',
                    resize: '',
                    s_date: '2022.06.23',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'support',
                    s_id: ['workView'],
                    link: '/support/workView',
                    resize: '',
                    s_date: '2022.06.23',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'support',
                    depth2: '통합검색',
                    s_id: ['tsearch'],
                    link: '/support/tsearch',
                    resize: '',
                    s_date: '2022.06.23',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'support',
                    depth2: '고객센터',
                    depth3: '매뉴얼',
                    s_id: ['manual'],
                    link: '/support/manual',
                    resize: '',
                    s_date: '2022.06.23',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'support',
                    depth3: '문의하기',
                    s_id: ['askWrite'],
                    link: '/support/askWrite',
                    resize: '',
                    s_date: '2022.06.23',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'support',
                    depth3: '문의내역',
                    s_id: ['askList'],
                    link: '/support/askList',
                    resize: '',
                    s_date: '2022.06.23',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'support',
                    depth3: '내문의내역',
                    s_id: ['myAskList'],
                    link: '/support/myAskList',
                    resize: '',
                    s_date: '2022.06.23',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'support',
                    depth2: '',
                    s_id: ['myAskView'],
                    link: '/support/myAskView',
                    resize: '',
                    s_date: '2022.06.23',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: 'division',
                    depth1: 'collaboration Board',
                    depth2: '협업보드 목록',
                    s_id: ['collaboBoard'],
                    link: '/collaboBoard/collaboBoardList',
                    resize: '',
                    s_date: '2022.08.09',
                    e_date: '2022.08.17',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'collaboration Board',
                    depth2: '협업보드 목록',
                    s_id: ['collaboBoard'],
                    link: '/collaboBoard/collaboBoardRecent',
                    resize: '',
                    s_date: '2022.08.09',
                    e_date: '2022.08.17',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: 'division',
                    depth1: 'setting',
                    depth2: '환경 설정',
                    depth3: '개인 정보',
                    s_id: ['setting'],
                    link: '/setting/settingInfo',
                    resize: '',
                    s_date: '2022.09.02',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'setting',
                    depth2: '환경 설정',
                    depth3: '홈화면 설정',
                    s_id: ['setting'],
                    link: '/setting/settingHome',
                    resize: '',
                    s_date: '2022.09.30',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'setting',
                    depth2: '환경 설정',
                    depth3: '알림 설정',
                    s_id: ['setting'],
                    link: '/setting/settingNotice',
                    resize: '',
                    s_date: '2022.09.02',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'setting',
                    depth2: '환경 설정',
                    depth3: '모바일초기화',
                    s_id: ['setting'],
                    link: '/setting/mobileReset',
                    resize: '',
                    s_date: '2022.11.25',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: 'division',
                    depth1: 'club',
                    depth2: '동호회',
                    depth3: '메인',
                    s_id: ['club'],
                    link: '/club/clubMain',
                    resize: '',
                    s_date: '2022.10.03',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'club',
                    depth2: '동호회',
                    depth3: '메인 (뷰모드 변경)',
                    s_id: ['club'],
                    link: '/club/clubMain2',
                    resize: '',
                    s_date: '2022.10.03',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'club',
                    depth2: '동호회',
                    depth3: '검색결과',
                    s_id: ['club'],
                    link: '/club/clubSearch',
                    resize: '',
                    s_date: '2022.10.03',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'club',
                    depth2: '동호회',
                    depth3: '목록',
                    s_id: ['club'],
                    link: '/club/clubList',
                    resize: '',
                    s_date: '2022.10.03',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'club',
                    depth2: '동호회',
                    depth3: '공지사항',
                    s_id: ['club'],
                    link: '/club/clubNoticeList',
                    resize: '',
                    s_date: '2022.10.03',
                },
                {
                    division: '',
                    depth1: 'club',
                    depth2: '동호회',
                    depth3: '목록(임시저장함)',
                    s_id: ['club'],
                    link: '/club/clubTempList',
                    resize: '',
                    s_date: '2022.01.10',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: 'division',
                    depth1: 'guide',
                    depth2: 'step01',
                    depth3: '',
                    s_id: ['guide'],
                    link: '/guide/guideStep_01',
                    resize: '',
                    s_date: '2023.01.13',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'guide',
                    depth2: 'step02',
                    depth3: '',
                    s_id: ['guide'],
                    link: '/guide/guideStep_02',
                    resize: '',
                    s_date: '2023.01.13',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'guide',
                    depth2: 'step03',
                    depth3: '',
                    s_id: ['guide'],
                    link: '/guide/guideStep_03',
                    resize: '',
                    s_date: '2023.01.13',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'guide',
                    depth2: 'step04',
                    depth3: '',
                    s_id: ['guide'],
                    link: '/guide/guideStep_04',
                    resize: '',
                    s_date: '2023.01.13',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },
                {
                    division: '',
                    depth1: 'guide',
                    depth2: 'step05',
                    depth3: '',
                    s_id: ['guide'],
                    link: '/guide/guideStep_05',
                    resize: '',
                    s_date: '2023.01.13',
                    e_date: '',
                    ing: '완료',
                    status: 'fin',
                    etc: '',
                },

            ]
        }
    },
    computed: {
        totalCount() {
            return this.items.length
        },
        ingCount() {
            return this.items.filter(i => i.status === 'ing').length;
        },
        completeCount() {
            return this.items.filter(i => i.status === 'fin').length;
        },
        notCompleteCount() {
            return this.totalCount - this.completeCount - this.ingCount
        },
        per() {
            return (this.completeCount / this.totalCount) * 100
        }
    },
    methods: {

    },
})
</script>

<style lang="css" scoped>
.wrap {padding:10px}
table {border-collapse:collapse;border-spacing:0;}
table th, strong {font-weight:normal;}
h1{
    margin:0 0 10px 0;
    text-align:center;
    font-size:36px;
    color:#000
}
a {text-decoration:none;}
a:hover {text-decoration:underline;}
.header::after {clear: both; content: ''; display: block;}
.header p {float: left;}
.header p + p {float:right}
table {
    width:100%;
    margin-top:5px;
    border-top:2px solid #1e61a8;
}
table th, table td{
    padding:5px 7px;
    border-left:1px solid #ccc; border-bottom:1px solid #ccc;
    box-sizing: border-box;
    background-color: #fff;
    font-size: 15px;
}
table th:rowspan + th, table td:rowspan + td{border-left:1px solid #ccc;}
td.lineli, th.lineli {border-left:1px solid #ccc !important;}
table th:first-child, table td:first-child{border-left:0 none}
table thead th {
    font-family:'ngB';
    font-size:15px;
    color:#000;
    border-bottom:1px solid #ccc;
    background-color:#f2f2f2;
}
.no, .start_date, .end_date, .work {
    text-align:center;
    padding:5px 0
}

.lastmdate {color: #1155CC;}
.stand_by {color:#777;}
.ing {color:#4848D4 !important;}
.fin, .per, .end {color:#ff0000 !important;}

.division td{border-top:2px solid #37b2d3}
.div td{border-top:2px solid #7e8e9e}

</style>
